### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by ghost** [metaodi/ancestors#5]
There is a bug with birth & death dates. Eg.
https://tools.wmflabs.org/family/ancestors.php?q=Q18913569
https://tools.wmflabs.org/family/ancestors.php?q=Q3586232

**Comment by metaodi** [comment]
Thanks for reporting this, the date format seems to have changed. I'll look into it.

**Comment by metaodi** [comment]
Okay it's fixed now. It either extract the correct date (apparently the date format from the API response has changed), or it simply tries to extract the year if the date cannot be parsed correctly.
